save_all_PSF: False
savedir: 'grid_search'
experiment_tag: 'delay'
oopao_path: 'AO_OOPAO'
param_file: 'Conf.parameter_fileRAZOR_SHWFS'

r0: 0.1
L0: 30
fractionalR0: [1]
windSpeed: [2]
windDirection: [0]
altitude: [0]

nLoop: 10000
gainCL: 0.225
gain_list: [0.15,0.2,0.25,0.3,0.35]
leak: 0.99
frames_per_sec: 500
delay: 0

initial_sigma: 0.05
iters: 20
max_ts: 500
n_history: 20
T: 5
data_shape: 11
device: 'cuda:0'
warmup_ts: 2
contrast: False
batch_size: 32

